{
 "title": "Tarpit",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "2h",
 "panels": [
  {
   "title": "Total Countries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tarpit",
     "rawSql": "SELECT COUNT(iso_code) FROM tarpit.land LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total IPs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tarpit",
     "rawSql": "SELECT COUNT(ip) FROM tarpit.server LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tarpit",
     "rawSql": "SELECT COUNT(ip) FROM tarpit.verbindungs_eintrag WHERE eintrag_typ = 'CONNECTED' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Most Connections (IP)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tarpit",
     "rawSql": "SELECT v.ip AS IP, l.land_name AS Country, COUNT(*) AS Connections FROM tarpit.verbindungs_eintrag v LEFT JOIN server s ON s.ip = v.ip LEFT JOIN land l ON s.land = l.iso_code WHERE v.eintrag_typ = 'CONNECTED' GROUP BY IP ORDER BY Connections DESC, IP LIMIT 1"
    }
   ]
  },
  {
   "title": "Most Connections (Country)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tarpit",
     "rawSql": "SELECT l.land_name AS Country, COUNT(*) AS Connections FROM tarpit.verbindungs_eintrag ve LEFT JOIN tarpit.server s ON ve.ip = s.ip LEFT JOIN tarpit.land l ON s.land = l.iso_code WHERE ve.eintrag_typ = 'CONNECTED' GROUP BY Country ORDER BY Connections DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Top 10 IPs",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "tarpit",
     "rawSql": "SELECT v.ip AS IP, l.land_name AS Country, COUNT(*) AS Connections FROM tarpit.verbindungs_eintrag v LEFT JOIN server s ON s.ip = v.ip LEFT JOIN land l ON s.land = l.iso_code WHERE v.eintrag_typ = 'CONNECTED' GROUP BY IP ORDER BY Connections DESC, IP LIMIT 10 "
    }
   ]
  },
  {
   "title": "Top countries by connections",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT l.land_name AS Country, COUNT(*) AS Connections FROM tarpit.verbindungs_eintrag ve LEFT JOIN tarpit.server s ON ve.ip = s.ip LEFT JOIN tarpit.land l ON s.land = l.iso_code WHERE ve.eintrag_typ = 'CONNECTED' GROUP BY Country"
    }
   ]
  },
  {
   "title": "Connections over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT ve.zeitstempel AS time_sec, COUNT(*) AS value FROM tarpit.verbindungs_eintrag ve WHERE ve.eintrag_typ = 'CONNECTED' GROUP BY UNIX_TIMESTAMP(ve.zeitstempel) DIV 1800 ORDER BY ve.zeitstempel"
    }
   ]
  }
 ]
}